version: "3.5"
services:
  rosnode:
    image: rosnode
    build: ./rosnode
  foxglove:
    image: ghcr.io/foxglove/studio
    ports:
      - 8080:8080
  foxglove-bridge:
    image: husarion/foxglove-bridge:humble-0.7.2-20231013
    ports:
      - 8766:8766
    command: ros2 launch foxglove_bridge foxglove_bridge_launch.xml port:=8766

